name: Send Push Update
on:
  push:
    branches:
      - main
    paths:
      - 'version.json'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Extraer versión
        id: version
        run: |
          VERSION=$(jq -r '.latestVersion' version.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Instalar Firebase Admin
        run: npm install firebase-admin

      - name: Ejecutar Script de Notificación
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          node -e "
          const { initializeApp, cert } = require('firebase-admin/app');
          const { getMessaging } = require('firebase-admin/messaging');
          
          const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);
          initializeApp({ credential: cert(serviceAccount) });
          
          const message = {
            notification: {
              title: '¡Nueva Actualización ' + process.env.VERSION + '!',
              body: 'WOSH!!! Y DESDE EL CIELO ACABA DE CAER UNA NUEVA ACTUALIZACIÓN NO ME DEJES ESPERANDO, ENTRA YA!!!!'
            },
            topic: 'all_users'
          };
          
          getMessaging().send(message)
            .then((response) => console.log('Éxito:', response))
            .catch((error) => { console.error('Error:', error); process.exit(1); });
          "